[pyprland]
plugins = [
 # "expose",
 # "fetch_client_menu",
 # "lost_windows",
 # "magnify",
 "scratchpads",
 # "shift_monitors",
 "toggle_special",
 # "workspaces_follow_focus",
]


[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=scratchpads.term"
class = "scratchpads.term"
size = "80% 40%"
max_size = "1920px 100%"
margin = 45 # Default value is 60
restore_focus = false
smart_focus = false
lazy = true
# unfocus = 'hide'


